---
title: Brett Chalupa
description: Independent full stack web application developer and designer based in Portland, OR
url: http://www.brettchalupa.com
logo: /image/brett_chalupa.jpg
twitter:
  username: brettchalupa
social:
  links:
    - https://twitter.com/brettchalupa
author:
  twitter: brettchalupa
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: ":title"
  talks:
    title: Talks
    output: true
    permalink: ":title"
  uploads:
    title: Uploads
    output: true
name: Brett Chalupa
highlighter: rouge
markdown: kramdown
permalink: ":title"
gems:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
