---
title: Brett Chalupa
timezone: America/Detroit
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: ":title"
  talks:
    title: Talks
    output: true
    permalink: ":title"
  works:
    title: Works
    output: true
    permalink: ":title"
  brief_moments:
    title: Brief Moments of Life
    output: true
    permalink: ":title"
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      description: 
  - scope:
      path: ''
      type: brief_moments
    values:
      layout: chapter
description: 'Writer, comic artist, and software developer based in Michigan.'
url: http://www.brettchalupa.com
logo: "/img/brett_chalupa.jpg"
google_site_verification: h9LmQSzbCwC5a0Oc1q6qAqQgApXhfsS7p13JFHFQD0Q
name: Brett Chalupa
highlighter: rouge
markdown: kramdown
permalink: ":title"
plugins:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
