---
title: Brett Chalupa
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: ":title"
  talks:
    title: Talks
    output: true
    permalink: ":title"
  uploads:
    title: Uploads
    output: true
name: Brett Chalupa
highlighter: rouge
markdown: kramdown
permalink: ":title"
gems:
- jemoji
- jekyll-sitemap
- jekyll-feed
